name: C/C++ CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt6
        run: sudo apt-get update && sudo apt-get install -y qt6-base-dev qt6-tools-dev qt6-tools-dev-tools

      - name: Configure with CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build with CMake
        run: cmake --build build -- -j$(nproc)

      - name: Run tests
        run: ctest --test-dir build --output-on-failure

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install aqtinstall
        run: pip install aqtinstall

      - name: Install Qt 6.10.0 (MSVC 2022)
        run: python -m aqt install-qt windows desktop 6.10.0 win64_msvc2022_64 --outputdir ${{ github.workspace }}/Qt

      - name: Set up MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake
        run: cmake -S . -B build -G "NMake Makefiles" -DCMAKE_PREFIX_PATH="${{ github.workspace }}/Qt/6.10.0/msvc2022_64"

      - name: Build
        run: cmake --build build
